apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: flink-jobs
  name: basic-example-1
spec:
  image: flink-hive-s3-custom:latest
  flinkVersion: v1_18
  mode: standalone
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "5"
    state.savepoints.dir: s3://test/savepoins
    state.checkpoints.dir: s3://test/checkpoints
    s3.endpoint: http://minio-svc.minio-dev:9000
    s3.path.style.access: "true"
    s3.access-key: minioadmin
    s3.secret-key: minioadmin
    execution.checkpointing.interval: "10000"
    table.catalog.myhivecatalog.type: hive
    table.catalog.myhivecatalog.default-database: default
    table.catalog.myhivecatalog.hive-conf-dir: ./conf
    table.default-catalog: myhivecatalog
    table.default-database: default
  ingress:
    template: "/{{namespace}}/{{name}}(/|$)(.*)"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      serviceAccount: flink
      containers:
        - name: flink-main-container
          env:
            - name: ENABLE_BUILT_IN_PLUGINS
              value: flink-s3-fs-presto-1.18.1.jar
          volumeMounts:
            - mountPath: /opt/flink/data
              name: flink-data
          command: [ 'sh','-c','curl https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-hive-3.1.3_2.12/1.18.1/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar -o ./lib/hive/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar' ]
      volumes:
        - name: flink-data
          emptyDir: { }
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1