apiVersion: v1
kind: Service
metadata:
  labels:
    app: hms
  name: hms-svc
  namespace: hms-dev
spec:
  ports:
  - name: thrift
    port: 9083
    protocol: TCP
    targetPort: 9083
  selector:
    app: hms
  type: ClusterIP
status:
  loadBalancer: {}